### ISSUE TITLE
Adding Social Media Links to the Footer of README

### ISSUE THREAD

**Issue by amiya-cyber** [Trisha-tech/OnlineBookSales#669] opened 2024-11-02 07:41 UTC
This READ ME lacks a contact us section.
We can Add a visually appealing footer to the README that includes links to key social media profiles, making it easy for users to connect and stay updated. The footer should align with the project's branding, feature accessible icons (e.g., GitHub, Twitter, LinkedIn), and be mobile-friendly. Each link must be verified to open correctly, ideally in a new tab where possible. This enhancement will improve user engagement and provide quick access to our social platforms.

please assign and add level2 
![2024-11-01 (6)](https://github.com/user-attachments/assets/290e92f1-5aa3-41e8-bf00-108a8c82c564)

**Comment by charan2r** [comment] 2024-11-02 13:53
hi, can you assign this to me?

**Comment by mridulsaggi** [comment] 2024-11-07 18:05
the issue is already resolved

**Closed by mridulsaggi** 2024-11-07 18:05 UTC
Labels: gssoc-ext, hacktoberfest-accepted
